### ISSUE TITLE
Ingliskeelne Demokraatia Töövihik

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/dtv#20]
Alustuseks tekstid kuskile tabelisse.

**Comment by karlpallo** [comment]
Eng-tõlked siin, võin ise tabelisse kopeerida ja üle timmida: 
https://docs.google.com/document/d/1gQLqCOCjVr6hyZ4Av2Fz_YxEukvk97HqIrn9whoUiCM/edit

**Comment by moll** [comment]
DTV tõlked leiab https://docs.google.com/spreadsheets/d/10al7Urlb1Gv16P8TY5Wu3cmu9n6iHiRnVHu7kRmHg2U/edit#gid=0 tabelist. 

@karlpallo, on sul kuskil ingliskeelne logo ka DTV-le?

**Comment by moll** [comment]
Potentsiaalselt saab ingliskeelsest PDFist või mujalt võtta ka ingliskeelse taustapildi https://demokraatia.rahvaalgatus.ee/eelarve lehe jaoks.

**Comment by moll** [comment]
Tänaseks on ingliskeelne DTV juba laivis.
