### ISSUE TITLE
Isikuandmete automaatne kustutamine

### ISSUE THREAD

**Issue by karlpallo** [rahvaalgatus/dtv#21]
1) Kaasava eelarve lehel ei ole vajadust hoida hääletajate nimesid/isikukoode pärast hääletust alles ning nende käsitsi kustutamine ei ole mõistlik. Nende kustumine peaks olema automatiseeritud. St hääletuse lõppedes, ühe nädala möödumisel (puhveraeg juhuks kui kool soovib taasavada hääletust, kuupäev läks alguses valesti vms) kustutatakse hääletajate andmed, aga hääletuse resultaat (ehk hääled ideede poolt) jäävad alles.

2) Õpetajate isikukood/nimi (kes on administraatorid oma kooli pesas) peaksid automaatselt kustuma aasta möödudes juhul kui nad ei ole vahepeal sisse loginud (loogika siin on, et kui kool kasutab regulaarselt tööriista-teeb kord aastas kaasavat eelarvet, siis ei ole vaja talle koolis administraatori õiguseid uuesti anda). 
Õpilaste ja kõigi teiste sisselogimise info peaks kustuma aasta möödudes juhul kui nad ei ole vahepeal sisse loginud. Oluline oleks, et ideed/kool/hääletus jääksid alles, aga kuna kaasava eelarve projekt algusest lõpuni võib maksimaalselt võtta aega ühe aasta, siis meil ei ole vajadust nende infot kauemaks ideedega seotuks jätta. Aasta on põhjendatud, sest kui õppeaasta alguses lisavad õpilased ideid ning hääletus toimub kevadel, siis nad saavad selle aja jooksul neid muuta.

**Comment by moll** [comment]
- Lahtine on, mida tuleks teha eelarvetega, mis pole kunagi alanud, kuid sisaldavad juba õpilaste isikukoode.
- Sama õpetajatega, kes pole kunagi sisse loginud, kuid kelle isikukoodi on admin kooli juurde lisanud. Tehniliselt pole neil kontot.
